version: '3'
services:
  back-end:
    build:
      context: .
      dockerfile: dockerfile-backend
    ports:
      - "3000:3000"
    networks:
      - mi-red
    container_name: expressapi
  front-end:
    build:
      context: .
      dockerfile: dockerfile-frontend
    ports:
      - "4200:4200"
    networks:
      - mi-red
    container_name: angularapp
networks:
  mi-red:
    name: mi-red