version: '3'
services:
  back-end:
    build:
      context: .
      dockerfile: dockerfile-express
    ports:
      - "3000:3000"
    networks:
      - network
    container_name: expressapi
  front-end:
    build:
      context: .
      dockerfile: dockerfile-angular
    ports:
      - "4200:4200"
    networks:
      - network
    container_name: angularapp
networks:
  network:
    name: network